### ISSUE TITLE
Troubles with toolboxpp.hpp

### ISSUE THREAD

**Issue by com-master** [MinterTeam/cpp-minter#1]
fatal error: toolboxpp.hpp: No such file or directory
   11 | #include <toolboxpp.hpp>
Просто не ставиться

**Comment by edwardstock** [comment]
@com-master скоро будет большое обновление сдк (возможно до 6 марта), все поправится

**Comment by edwardstock** [comment]
@com-master а можете подробнее описать какую версию, как собираете, как подключаете и тд?
